scripts/python/src/fodt/extract_appendix.py
=> Extracted Appendix C from main.fodt

parts/appendices/D.fodt, scripts/python/src/fodt/extract_appendix.py
Builds on #166, which should be merged first.
=> Extracted Appendix D from main.fodt

parts/appendices/D.fodt, scripts/python/src/fodt/extract_appendix.py
Builds on #167, which should be merged first.
=> Extracted Appendix F from main.fodt

parts/appendices/D.fodt, parts/appendices/E.fodt, scripts/python/src/fodt/extract_appendix.py
Builds on #168, which should be merged first.
Appendix E's heading tag had a missing property `text:continue-numbering="true"` which made the numbering for the next appendix to restart on A instead of continuing on F. 
Fixes #165
=> Fixes a bug in the Appendix heading numbering

parts/chapters/subsections/12.3/GCONPROD.fodt
ORAT, WRAT, GRAT and LRAT changed to OIL etc.
Removed RESV
Added description of COMB, INJ, and POTN
(sorry too many changes to easily use a text editor for this one)
=> Update GCONPROD item 10

parts/chapters/subsections/8.3/GASDENT.fodt
Also remove sentence "The reference pressure for this table is given by the VISCREF keyword in the PROPS section." as I don't think it is relevant for this keyword.
=> GASDENT add description of correlation

parts/chapters/subsections/8.3/WATDENT.fodt
Also remove sentence "The reference pressure for this table is given by the VISCREF keyword in the PROPS section." as I don't think it is relevant for this keyword.
Add sentence "Note this is an OPM Flow keyword used with OPM Flow’s black-oil thermal model that is not available in the commercial simulator’s black-oil thermal formulation." to be consistent with GASDENT
=> WATDENT add description of correlation

parts/chapters/subsections/8.3/OILDENT.fodt
Also remove sentence "The reference pressure for this table is given by the VISCREF keyword in the PROPS section." as I don't think it is relevant for this keyword.
=> OILDENT add description of correlation

parts/chapters/subsections/10.3/TBLK.fodt
=> Update TBLK example

parts/appendices/A.fodt
Thanks to @gdfldm for spotting this.
=> Fixed typo in GASDENT in Appendix A

parts/appendices/A.fodt
Delete duplicate row for SGWFLET in Appendix A. Thanks to @gdfldm for spotting this.
@gdfldm Can you test this? I am not able to open `main.fodt` myself and check if it looks ok.
=> Delete duplicate row in Appendix A

parts/appendices/A.fodt
Fixes a typo in Appendix A. See #223 for more information.
=> Fix typo in Appendix A

parts/appendices/A.fodt, parts/chapters/subsections/8.3/ROCKTAB.fodt
fodt-set-keyword-status --keyword ROCKTAB --color green
=> Mark ROCKTAB as supported V2

parts/appendices/A.fodt
fodt-set-keyword-status --keyword ACTION --color orange 
fodt-set-keyword-status --keyword ACTIONG --color orange 
fodt-set-keyword-status --keyword ACTIONR --color orange
=> Mark ACTION, ACTIONG and ACTIONR as unsupported V2

parts/appendices/A.fodt, parts/chapters/subsections/10.3/SKIP.fodt, parts/chapters/subsections/12.3/SKIP.fodt, parts/chapters/subsections/4.3/SKIP.fodt, parts/chapters/subsections/5.3/SKIP.fodt, parts/chapters/subsections/6.3/SKIP.fodt, parts/chapters/subsections/7.3/SKIP.fodt, parts/chapters/subsections/8.3/SKIP.fodt, parts/chapters/subsections/9.3/SKIP.fodt
This keyword is now partially supported but does not support nesting
=> Update SKIP keyword for 2024-04

parts/appendices/A.fodt
For background see https://github.com/OPM/opm-reference-manual/pull/282#issuecomment-2152581962
Fixes the link to SGU from Appendix A to Chapter 8.
=> Fix SGU link in appendix A

parts/chapters/sections/11/2.fodt
Option specific variables - CO2STORE model: type changed from Volume to Moles
=> Update SUMMARY variables GCDI, GCDM and WCD type -> Moles

parts/chapters/subsections/10.3/RPTRST.fodt
Update RPTRST tables to include additional arrays including:
FREQ, RESIDUAL, CONV, 
XMFCO2, XMFH2, YMFWAT
Array required to restart Polymer, MICP, Hysteresis, PRECSALT, etc. runs
=> Update RPTRST for 2024-04

parts/chapters/subsections/12.3/WTEST.fodt
plus some formatting and rewording,
=> Update WTEST now supports TEST=G (group)

parts/appendices/A.fodt, parts/chapters/subsections/12.3/UDT.fodt
partially supported for one-dimensional tables
=> Update UDT with description and partial support

parts/chapters/subsections/12.3/PYACTION.fodt
The run() style scripts have been deprecated. 
The description of the scripts has been updated along with the examples.
Also some updates to the text and tiding of the xml.
=> Update PYACTION to use new style python scripts

parts/chapters/sections/11/2.fodt
Group/Node pressure in a production network based on rates at end of timestep (OPM Flow specific).
=> Updated SUMMARY added GNETPR and NPR

parts/chapters/subsections/10.3/BC.fodt
Update description to say BC has been replaced by BCCON and BCPROP 
Add page break before description
=> Update BC Keyword

parts/appendices/A.fodt
fodt-set-keyword-status --keyword BCPROP --color green --opm-flow 
fodt-set-keyword-status --keyword BCCON --color green --opm-flow
=> Mark BCPROP and BCCON as OPM Flow specific

parts/appendices/A.fodt
fodt-set-keyword-status --keyword DIFFAGAS --color green --opm-flow
fodt-set-keyword-status --keyword DIFFAWAT --color green --opm-flow
=> Mark DIFFAGAS and DIFFAWAT as OPM Flow in Appendix A

parts/appendices/A.fodt
fodt-set-keyword-status --keyword GASVISCT --color green
=> Mark GASVISCT as Supported in Appendix A

parts/chapters/subsections/10.3/MESSAGES.fodt, parts/chapters/subsections/11.3/MESSAGES.fodt, parts/chapters/subsections/12.3/MESSAGES.fodt, parts/chapters/subsections/4.3/MESSAGES.fodt, parts/chapters/subsections/5.3/MESSAGES.fodt, parts/chapters/subsections/6.3/MESSAGES.fodt, parts/chapters/subsections/7.3/MESSAGES.fodt, parts/chapters/subsections/8.3/MESSAGES.fodt, parts/chapters/subsections/9.3/MESSAGES.fodt
=> Fix table refs in MESSAGES

parts/chapters/sections/8/2.fodt
~I was unable to get table references between sub-documents to work, so I have used a reference to the section instead.~
Fixed table references in section 2.4
=> Fix Table Refs in Section 2 4

parts/chapters/subsections/8.3/GSF.fodt, parts/chapters/subsections/8.3/WSF.fodt
=> Change WSF title

parts/appendices/A.fodt
plus text colour for BCCON and BCPROP
=> SALINITY OPM FlowS -> OPM Flow in Appendix A

parts/chapters/sections/11/2.fodt
'CO2 Dissolved and immobile in the gas phase' -> 'CO2 Immobile in the gas phase' etc.
=> Correct definition of CO2STORE summary vectors

parts/chapters/subsections/5.3/H2STORE.fodt
Removed references to convective mixing (DRSDTCON)
=> H2STORE remove references to DRSDTCON

parts/chapters/subsections/6.3/OPERATE.fodt
pow(10, alpha * X + beta) -> pow(10, alpha + beta * X)
=> OPERATE correct definition of SLOG

parts/chapters/subsections/6.3/OPERATER.fodt
pow(10, alpha * X + beta) -> pow(10, alpha + beta * X)
=> OPERATER correct definition of SLOG

parts/chapters/subsections/12.3/SOURCE.fodt, parts/chapters/subsections/5.3/CO2SOL.fodt, parts/chapters/subsections/5.3/EOS.fodt, parts/chapters/subsections/5.3/H2SOL.fodt, parts/chapters/subsections/8.3/ACF.fodt, parts/chapters/subsections/8.3/ACTCO2S.fodt, parts/chapters/subsections/8.3/BIC.fodt, parts/chapters/subsections/8.3/DIFFAGAS.fodt, parts/chapters/subsections/8.3/DIFFAWAT.fodt, parts/chapters/subsections/8.3/EOS.fodt, parts/chapters/subsections/8.3/MW.fodt, parts/chapters/subsections/8.3/PCRIT.fodt, parts/chapters/subsections/8.3/QHRATING.fodt, parts/chapters/subsections/8.3/SOMGAS.fodt, parts/chapters/subsections/8.3/SOMWAT.fodt, parts/chapters/subsections/8.3/TCRIT.fodt, parts/chapters/subsections/8.3/TEMPNODE.fodt, parts/chapters/subsections/8.3/TEMPTVD.fodt, parts/chapters/subsections/8.3/THCO2MIX.fodt, parts/chapters/subsections/8.3/TRNHD.fodt, parts/chapters/subsections/8.3/VCRIT.fodt, parts/chapters/subsections/9.3/EOSNUM.fodt
Change background from transparent to grey
Correct highlighted section: TEMPNODE, TRNHD, TEMPTVD
=> Format header colour

parts/chapters/subsections/12.3/WCONINJE.fodt, parts/chapters/subsections/12.3/WCONPROD.fodt
Based on definitions in
opm/input/eclipse/share/keywords/*
=> Mark items that support UDAs: WCONINJE, WCONPROD

parts/chapters/subsections/6.3/ADDREG.fodt, parts/chapters/subsections/6.3/COPYREG.fodt, parts/chapters/subsections/6.3/EQUALREG.fodt, parts/chapters/subsections/6.3/MULTIREG.fodt, parts/chapters/subsections/6.3/MULTREGD.fodt, parts/chapters/subsections/6.3/MULTREGH.fodt, parts/chapters/subsections/6.3/MULTREGP.fodt, parts/chapters/subsections/6.3/MULTREGT.fodt
=> MULTREGD and MULTREGH add note on defaulted region numbers

parts/chapters/subsections/12.3/GCONINJE.fodt, parts/chapters/subsections/12.3/GCONPRI.fodt, parts/chapters/subsections/12.3/GCONPROD.fodt, parts/chapters/subsections/12.3/GCONSALE.fodt, parts/chapters/subsections/12.3/GCONSUMP.fodt, parts/chapters/subsections/12.3/GECON.fodt
plus some text updates and typos
=> Mark items that support UDAs: GCONSUMP, GCONINJE, GCONSALE, GCONPROD, GECON, GCONPRI

.github/workflows/ci.yml
Retrying #276. It was reverted (#423) due to this failure: https://github.com/OPM/opm-reference-manual/pull/423#issuecomment-2474776547
=> Also run github action tests for docker directory

scripts/python/src/fodt/keyword_linker.py
Extends the script to handle keywords in quotes represented by an `&quot;` entity or keywords followed by apostrophes represented by an `&apos;` entity. We should not link these keywords.
=> Extend keyword linking script to handle quoted keywords

scripts/python/src/fodt/keyword_linker.py
Fix link keywords script such that it does not add links inside `office:binary` sections. These sections contain image data encoded as base64, and should not be considered as normal text.
=> Update link keywords script: Do not add links inside office:binary-data sections

scripts/python/pyproject.toml, scripts/python/src/fodt/check_links_office_binary.py, scripts/python/src/fodt/keyword_linker.py
Builds on #442 which should be merged first.
Updated the keyword linking script to handle chapter `.fodt` files like `1.fodt`.
=> Update keyword linking script to handle chapters

parts/chapters/1.fodt
Used the script in #444 to add links for keywords in chapter 1.
=> Added links for keywords in chapter 1

parts/chapters/subsections/6.3/ADD.fodt, parts/chapters/subsections/6.3/ADDREG.fodt, parts/chapters/subsections/6.3/COPY.fodt, parts/chapters/subsections/6.3/COPYREG.fodt, parts/chapters/subsections/6.3/EQUALREG.fodt, parts/chapters/subsections/6.3/EQUALS.fodt, parts/chapters/subsections/6.3/MULTIPLY.fodt, parts/chapters/subsections/6.3/MULTIREG.fodt, parts/chapters/subsections/6.3/OPERATE.fodt, parts/chapters/subsections/6.3/OPERATER.fodt
=> Add support for EQUALREG keyword

parts/chapters/subsections/8.3/EHYSTR.fodt
=> Add support for EHYSTR(HYSTMOD) = 4

parts/appendices/B.fodt
Also minor updates to New Features
Builds on #420
=> Add draft of Improvements

parts/chapters/sections/11/2.fodt
GMIP, GMDS, GMGP add
GMTR, GMMO update definition
GMST, GMUS add
=> Update CO2STORE summary vectors

scripts/python/src/fodt/automatic_styles_filter.py, scripts/python/src/fodt/extract_chapters.py, scripts/python/src/fodt/extract_fonts.py, scripts/python/src/fodt/extract_metadata.py, scripts/python/src/fodt/extract_subsections.py, scripts/python/src/fodt/extract_tag_attrs.py, scripts/python/src/fodt/keyword_uri_map_generator.py, scripts/python/src/fodt/split_main.py, scripts/python/src/fodt/styles_filter.py
In PR #453, some import statements were adjusted incorrectly
=> Fix wrongly adjusted imports from #453

scripts/python/src/fodt/keyword_linker.py
Update keyword linker script to handle appendices.
=> Update keyword linker script

parts/chapters/sections/11/2.fodt
=> Add Gas Mass Injection Rate / Total SUMMARY vector

parts/chapters/subsections/5.3/THERMAL.fodt
TEMP is no longer an alias for THERMAL
=> THERMAL update table note

parts/chapters/3.fodt
=> Update Table 3.4 

parts/chapters/sections/12/2.fodt
Not sure how well this has worked. May need to double-click the equation in LibreOffice to update the image.
=> Correct equation 12.8

parts/chapters/subsections/8.3/PCFACT.fodt, parts/chapters/subsections/8.3/PERMFACT.fodt
Updated descriptions for https://github.com/OPM/opm-common/pull/4518, in draft mode for now.
=> Updates to PERMFACT and PCFACT

parts/chapters/sections/11/2.fodt
This is the last PR to document the changes in the `MICP` model introduced in https://github.com/OPM/opm-common/pull/4538. All four PRs in principle should be possible to merge them independently. Please let me know if something needs to be corrected before merging these PRs.
=> Summary vectors for MICP

parts/appendices/A.fodt, parts/chapters/subsections/8.3/PLYSHEAR.fodt, parts/chapters/subsections/8.3/SHRATE.fodt
Marked PLYSHEAR as unsupported
Updated description of SHRATE and marked as supported
(Used to LibreOffice to edit SHRATE)
=> Update PLYSHEAR and SHRATE

parts/chapters/sections/8/2.fodt
=> Format Table Borders Section 8

parts/chapters/subsections/12.3/GCONINJE.fodt
=> GCONINJE remove unnecessary pagebreak

parts/chapters/subsections/8.3/EHYSTR.fodt
by deleting blank line at end.
Plus tidy some formatting
=> Remove blank page after EHYSTR
