OPM/opm-reference-manual

- scripts/python/pyproject.toml
- scripts/python/src/fodt/add_keyword.py
- scripts/python/src/fodt/add_keyword_status.py
- scripts/python/src/fodt/automatic_styles_filter.py
- scripts/python/src/fodt/extract_appendix.py
- scripts/python/src/fodt/extract_chapters.py
- scripts/python/src/fodt/extract_fonts.py
- scripts/python/src/fodt/extract_metadata.py
- scripts/python/src/fodt/extract_section.py
- scripts/python/src/fodt/extract_subsections.py
- scripts/python/src/fodt/extract_tag_attrs.py
- scripts/python/src/fodt/extract_xml_tag.py
- scripts/python/src/fodt/helpers.py
- scripts/python/src/fodt/remove_bookmarks.py
- scripts/python/src/fodt/remove_chapters.py
- scripts/python/src/fodt/remove_elements.py
- scripts/python/src/fodt/remove_fonts.py
- scripts/python/src/fodt/remove_subsections.py
- scripts/python/src/fodt/set_fonts.py
- scripts/python/src/fodt/split_main.py
- scripts/python/src/fodt/styles_filter.py
- scripts/python/src/fodt/xml_helpers.py
- scripts/python/src/fodt/xml_sax_filter_all.py
Note: this PR builds on #170 which should be merged first.
Created a script that runs the Python `xml.sax` parser on all XML files and then writes back the content in the same way as LibreOffice writes XML. That is: it escapes `&`, `<`, `>`, `'`, and `"` and uses the short form `<tag/>` for empty tags instead of the long form  `<tag></tag>`.
By running this filter once on all files, we should hopefully get smaller PR diffs in the future since the Python scripts and LibreOffice should now agree on the format.
> Created script to cleanup XML files

- scripts/python/src/fodt/add_keyword.py
- scripts/python/src/fodt/add_keyword_status.py
- scripts/python/src/fodt/automatic_styles_filter.py
- scripts/python/src/fodt/extract_appendix.py
- scripts/python/src/fodt/extract_chapters.py
- scripts/python/src/fodt/extract_fonts.py
- scripts/python/src/fodt/extract_metadata.py
- scripts/python/src/fodt/extract_section.py
- scripts/python/src/fodt/extract_subsections.py
- scripts/python/src/fodt/extract_tag_attrs.py
- scripts/python/src/fodt/extract_xml_tag.py
- scripts/python/src/fodt/helpers.py
- scripts/python/src/fodt/remove_bookmarks.py
- scripts/python/src/fodt/remove_chapters.py
- scripts/python/src/fodt/remove_elements.py
- scripts/python/src/fodt/remove_fonts.py
- scripts/python/src/fodt/remove_subsections.py
- scripts/python/src/fodt/set_fonts.py
- scripts/python/src/fodt/split_main.py
- scripts/python/src/fodt/styles_filter.py
- scripts/python/src/fodt/xml_helpers.py
`xml.sax.saxutils.escape()` escapes only the three characters `&`, `<`, and `>`. But LibreOffice also escapes the characters `"` and `'`. So we should escape them as well in order not to get large PR diffs each time a Python script is modifying the XML files. Or each time LibreOffice is modifying an XML file that was previously written by a Python script.
> Escape quotes and apostrophes when writing XML files with the Python scripts

- scripts/python/pyproject.toml
- scripts/python/src/fodt/xml_filter_meta.py
- scripts/python/src/fodt/xml_handlers.py
Added script to run xml pass-through filter on the xml meta files. These files are used by the add-keyword script. So we should cleanup the meta files the same way we did for the .fodt files in https://github.com/OPM/opm-reference-manual/pull/172
> Added script to clean up meta files

- scripts/python/README.md
- scripts/python/src/fodt/add_keyword_status.py
Updated the `fodt-set-keyword-status` script to also handle the case when keyword is specific to OPM flow:
when the keyword is specific to OPM flow, the text "OPM Flow" is shown in the table as shown in the screenshot above. The script can now be run like this:
```
$  fodt-set-ketword-status --keyword=CSKIN --color=green --opm-flow
```
to put the text "OPM Flow" or just omit the flag `--opm-flow` to remove the text "OPM Flow".
Thanks to @gdfldm for the suggestion.
@gdfldm Can you test this?
> Update the set-keyword-status script

- scripts/python/src/fodt/constants.py
- scripts/python/src/fodt/helpers.py
- scripts/python/src/fodt/remove_span_tags.py
- scripts/python/tests/test_helpers.py
For background see #209.
Added a more advanced method to locate the `maindir` and `filename` arguments for usage with the Python scripts. This is useful because the Python scripts can be installed globally and then run from any directory. The original logic assumed that the Python scripts were run from `scripts/python`. Also added some unit tests.
> Added a more advanced method to locate the maindir from the Python scripts

- scripts/python/src/fodt/add_keyword.py
- scripts/python/src/fodt/constants.py
- scripts/python/src/fodt/create_subdocument.py
- scripts/python/src/fodt/helpers.py
- scripts/python/src/fodt/remove_subsections.py
- scripts/python/src/fodt/split_subdocument.py
- scripts/python/tests/test_helpers.py
This PR builds on #212, which should be merged first.
For background see #228. Updated the add-keyword script to handle empty tags.
> Fix add keyword

- parts/meta/sections/font-face-decls.xml
- parts/meta/sections/master-styles.xml
- parts/meta/sections/meta.xml
- parts/meta/sections/scripts.xml
- parts/meta/sections/settings.xml
- parts/meta/sections/styles.xml
- scripts/python/src/fodt/xml_filter_meta.py
- scripts/python/src/fodt/xml_handlers.py
A bug was introduced in #230 and #231 such that the xml header tag was added to all meta files.
This PR removes the headers from the meta files (introduced in #231) and fixes the `fodt-xml-sax-filter-meta` script to work correctly (not adding the header to the meta files)
Thanks to @gdfldm for spotting the problem.
> Fixed bug in fodt-xml-sax-filter-meta script

- parts/appendices/A.fodt
- scripts/python/src/fodt/add_keyword_status.py
For background see https://github.com/OPM/opm-reference-manual/pull/238#discussion_r1611595172.
A newline was accidentally gobbled up by the `fodt-set-keyword-status` script. Hopefully this change fixes the issue.
> Fixed a bug in the fodt-set-keyword-status script

- parts/appendices/A.fodt
For background see https://github.com/OPM/opm-reference-manual/pull/282
This fixes a spelling mistake in appendix A. This mistake seems to have  confused the add-keyword script such that it could add the keyword at the wrong position.
> Fix spelling mistake in appendix A

- scripts/python/src/fodt/add_keyword.py
- scripts/python/src/fodt/add_keyword_status.py
- scripts/python/src/fodt/constants.py
See https://github.com/OPM/opm-reference-manual/pull/282#issuecomment-2152755214 for background.
Use more precise regex in set-keyword-status script.
> Use more precise regex

- parts/chapters/sections/11/2.fodt
Field and Region level summary vectors have been added when using the CO2STORE option based on this definition as follows ([#5281](https://github.com/OPM/opm-simulators/pull/5281), [#4010](https://github.com/OPM/opm-common/pull/4010)): Gas Moles in the Immobile Gas Phase (Non-wetting relative permeability equals zero), Gas Moles in the Mobile Gas Phase (Non-wetting relative permeability greater than zero), Gas Mass in the Immobile Gas Phase, and Gas Mass in the Mobile Gas Phase.
Depends on #270
> Add SUMMARY variables GKDI and GKDM 

- parts/chapters/sections/11/2.fodt
Field and Region level summary vectors have been added when using the CO2STORE option based on this definition as follows ([#5281](https://github.com/OPM/opm-simulators/pull/5281), [#4010](https://github.com/OPM/opm-common/pull/4010)): Gas Moles in the Immobile Gas Phase (Non-wetting relative permeability equals zero), Gas Moles in the Mobile Gas Phase (Non-wetting relative permeability greater than zero), Gas Mass in the Immobile Gas Phase, and Gas Mass in the Mobile Gas Phase.
Depends on #271
> Add SUMMARY variables GKMO and GKTR

- parts/chapters/subsections/10.3/DATUMR.fodt
- parts/chapters/subsections/10.3/DATUMRX.fodt
- parts/chapters/subsections/8.3/PVTG.fodt
- parts/chapters/subsections/8.3/PVTGW.fodt
- parts/chapters/subsections/8.3/PVTGWO.fodt
Corrected minor typos in new supported keywords for 2024.04. Added missing terminating slashes for sub-table records of second table in examples for PVTG series of keywords.
> Minor edits #4

- parts/appendices/A.fodt
- parts/chapters/subsections/8.3/DISPERSE.fodt
Links to the DISPERSE keyword description seemed to be broken. This seems to be due to there being no space before the dash in the title of the page i.e. "DISPERSE- etc" not "DISPERSE - etc".
> Repair DISPERSE keyword

- parts/chapters/subsections/12.3/GRUPNET.fodt
- parts/chapters/subsections/12.3/GRUPTREE.fodt
Replaces PR #344
I have wrapped the Figure number 'Figure 12.4' in GRUPTREE in a reference and tried to give it a unique ref-name. This ref-name is then cross-referenced from GRUPNET. I have successfully tested the links in main.fodt and in the exported main.PDF.
> Fix figure reference in GRUPNET

- README.md
> README file add note on reviewing PRs

- parts/chapters/subsections/6.3/ADDREG.fodt
- parts/chapters/subsections/6.3/COPYREG.fodt
- parts/chapters/subsections/6.3/EQUALREG.fodt
- parts/chapters/subsections/6.3/MULTIREG.fodt
- parts/chapters/subsections/6.3/MULTREGD.fodt
- parts/chapters/subsections/6.3/MULTREGH.fodt
- parts/chapters/subsections/6.3/MULTREGP.fodt
- parts/chapters/subsections/6.3/MULTREGT.fodt
* If the REGION array is not indicated, the
* default region to use in the xxxREG keywords depends on the GRIDOPTS
* keyword:
*
* 1. If GRIDOPTS is present, and the NRMULT item is greater than zero,
* the xxxREG keywords will default to use the MULTNUM region.
*
* 2. If the GRIDOPTS keyword is not present - or the NRMULT item equals
* zero, the xxxREG keywords will default to use the FLUXNUM keyword.
*
> ADDREG, COPYREG, etc. and MULTREGP, MULTREGT, etc. Add Note on Default Region 

- scripts/python/pyproject.toml
- scripts/python/src/fodt/add_keyword.py
- scripts/python/src/fodt/constants.py
- scripts/python/src/fodt/create_subdocument.py
- scripts/python/src/fodt/extract_section.py
- scripts/python/src/fodt/extract_subsections.py
- scripts/python/src/fodt/helpers.py
- scripts/python/src/fodt/keyword_linker.py
- scripts/python/src/fodt/remove_span_tags.py
- scripts/python/src/fodt/remove_subsections.py
- scripts/python/src/fodt/set_fonts.py
- scripts/python/src/fodt/split_subdocument.py
- scripts/python/src/fodt/validate_automatic_styles.py
- scripts/python/tests/test_helpers.py
This script can be used to extract a mapping from keyword names to XML URI tag names. The mapping can be saved to a file and later be used to make keywords clickable. So the goal is to enable the user to click on a keyword referenced in a paragraph of text in the manual, and then automatically jump to the page where that keyword is defined.
The plan is to use the produced mapping in another script (yet to be written) that will convert keyword names into `<text:a xlink:href="some_uri" ...>KEYWORD_NAME</text:a>` which will make the text KEYWORD_NAME into a clickable link.
> Script to extract keyword URIs

- parts/chapters/subsections/6.3/MULTREGD.fodt
- parts/chapters/subsections/6.3/MULTREGH.fodt
- parts/chapters/subsections/6.3/MULTREGT.fodt
Add note on repeated combinations of regions (see https://github.com/OPM/opm-reference-manual/pull/402#discussion_r1828280552).
Fixed typos.
> Update MULTREGD, MULTREGH and MULTREGT

- docker/README.md
- docker/src/lodocker/constants.py
- docker/src/lodocker/helpers.py
- docker/src/lodocker/run_container.py
- docker/tests/test_find_git_root.py
For background see https://github.com/OPM/opm-reference-manual/pull/208#issuecomment-2134838443.
The git root will not always be 3 levels up from the filename. Added a more advanced method to find the git root. Also added a test case.
> Fixed bug in the run docker container script

- .github/workflows/ci.yml
Also run Python test cases in docker folder using GitHub action workflow.
> Also run github action tests for docker directory

- .github/workflows/ci.yml
Reverts OPM/opm-reference-manual#276
> Revert "Also run github action tests for docker directory"

- scripts/python/src/fodt/keyword_linker.py
Do not link keywords like "LGR" in the string "LGR-OPM1". See https://github.com/OPM/opm-reference-manual/pull/435#discussion_r1888930577 for more information
> Update link keywords script: Do not link keywords followed by a dash

- scripts/python/src/fodt/keyword_linker.py
Builds on #440 which should be merged first.
To avoid adding links from Figure captions, we check if we are inside a `draw:frame` element. See https://github.com/OPM/opm-reference-manual/pull/435#discussion_r1889142988 for more information
> Update link keywords script: Do not add links for figure captions

- scripts/python/pyproject.toml
- scripts/python/src/fodt/check_links_office_binary.py
- scripts/python/src/fodt/keyword_linker.py
Builds on #441 which should be merged first.
This script checks for erroneously inserted links to keywords in the `office:binary-data` sections in the keyword files. These links might have been inserted by the keyword linking script, see https://github.com/OPM/opm-reference-manual/pull/435#issuecomment-2553264255 for more information.
I ran this script on chapters 4-11 and no erroneous links where detected there (according to this script). I will check chapter 12 next.
> Script to check for erroneous links

- scripts/python/src/fodt/keyword_linker.py
These paragraphs contain verbatim monospaced text and should not be linked. See https://github.com/OPM/opm-reference-manual/pull/446#discussion_r1901703791 for more information
> Update keyword linking script to handle P603 paragraphs

- scripts/python/src/fodt/keyword_linker.py
- scripts/python/src/fodt/keyword_uri_map_generator.py
Builds on #465  which should be merged first.
We would like to avoid linking keywords in table captions, see https://github.com/OPM/opm-reference-manual/pull/470#issuecomment-2580490968 for more information.
> Update keyword linking script to handle table captions

- scripts/python/src/fodt/keyword_linker.py
Builds on #478, which should be merged first.
Updated keyword linking script to also update the URI of existing links if needed.
> Updated keyword linking script to also update the URI of existing links
